// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBBc0Fnbe74hQFtFCw841zldxRT3Swqdw',
    appId: '1:367637158841:web:5412a83031afad36c73468',
    messagingSenderId: '367637158841',
    projectId: 'ruanglensa',
    authDomain: 'ruanglensa.firebaseapp.com',
    storageBucket: 'ruanglensa.firebasestorage.app',
    measurementId: 'G-V6PDX1QN92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdDDBU3PTtPoIJX2RK3v25BsqbUj0tuQ',
    appId: '1:367637158841:android:dc48bbc821595de5c73468',
    messagingSenderId: '367637158841',
    projectId: 'ruanglensa',
    storageBucket: 'ruanglensa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GaeV_TiqCmVw8nTGWE7qervlec2eVjI',
    appId: '1:367637158841:ios:9c18dc735f08f458c73468',
    messagingSenderId: '367637158841',
    projectId: 'ruanglensa',
    storageBucket: 'ruanglensa.firebasestorage.app',
    iosBundleId: 'com.example.ruanglensa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GaeV_TiqCmVw8nTGWE7qervlec2eVjI',
    appId: '1:367637158841:ios:9c18dc735f08f458c73468',
    messagingSenderId: '367637158841',
    projectId: 'ruanglensa',
    storageBucket: 'ruanglensa.firebasestorage.app',
    iosBundleId: 'com.example.ruanglensa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBBc0Fnbe74hQFtFCw841zldxRT3Swqdw',
    appId: '1:367637158841:web:8b90fa08595daacec73468',
    messagingSenderId: '367637158841',
    projectId: 'ruanglensa',
    authDomain: 'ruanglensa.firebaseapp.com',
    storageBucket: 'ruanglensa.firebasestorage.app',
    measurementId: 'G-GPBE8SPF59',
  );

}